### ISSUE TITLE
invalid load key, '/12'

### ISSUE THREAD

**Issue by liu-x-p** [google-research/albert#217]
Finetuning on squadv2, when it loading eval features, i got some error, and don't know how to solve it, can you help me?
![2020-06-21 11-10-00屏](https://user-images.githubusercontent.com/58974386/85215875-01436a00-b3b1-11ea-97a1-dda7cd3f6b93.png)

**Comment by liu-x-p** [comment]
![2020-06-21 11-10](https://user-images.githubusercontent.com/58974386/85215894-38198000-b3b1-11ea-9296-fb1d856cdcd1.png)

**Comment by liu-x-p** [comment]
I0621 10:48:47.149592 139987104491264 run_squad_v2.py:338] Loading eval features from ...
Traceback (most recent call last):
  File "/home/omnisky/anaconda3/envs/squad/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/omnisky/anaconda3/envs/squad/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/omnisky/mount/NLP/albert/run_squad_v2.py", line 516, in <module>
    tf.app.run()
  File "/home/omnisky/anaconda3/envs/squad/lib/python3.6/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/omnisky/anaconda3/envs/squad/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/omnisky/anaconda3/envs/squad/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/home/omnisky/mount/NLP/albert/run_squad_v2.py", line 340, in main
    eval_features = pickle.load(fin)
_pickle.UnpicklingError: invalid load key, '\x12'.
