### ISSUE TITLE
[UNK] token in v2 models

### ISSUE THREAD

**Issue by kkkppp** [google-research/ALBERT#81]
I downloaded albert_xxl v2, in file assets/30k-clean.vocab entry for [UNK] looks like:

\<unk\>	0

while in tokenization.py it's :

class WordpieceTokenizer(object):
  """Runs WordPiece tokenziation."""

  def __init__(self, vocab, unk_token="[UNK]", max_input_chars_per_word=200):

So I'm getting error like below. Is it ok to modlfy tokenization.py or I'm doing something wrong?

    input_ids = tokenizer.convert_tokens_to_ids(ntokens)
  File "J:\albert\tokenization.py", line 269, in convert_tokens_to_ids
    return convert_by_vocab(self.vocab, tokens)
  File "J:\albert\tokenization.py", line 211, in convert_by_vocab
    output.append(vocab[item])
KeyError: '[UNK]'

**Comment by aarmstrong78** [comment]
I had a similar issue and my problem was that I wasn't setting the spm_model_file flag correctly, and therefore the tokeniser was falling back to the Basic & Wordpiece tokenisers which use [UNK]

**Comment by JKP0** [comment]
I have the same issue, anyone have a solution please help
>
`cd ALBERT`
/content/ALBERT

```
from ALBERT import tokenization
from ALBERT import tokenization_test
```
>

```
tokenizer=tokenization.FullTokenizer("/content/30k-clean.vocab")
tc=tokenizer.tokenize("Hello, my dog is cute")
ec=tokenizer.convert_tokens_to_ids(tc)
```
>logs
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-69-4fbb518387cd> in <module>()
      1 tokenizer=tokenization.FullTokenizer("/content/30k-clean.vocab")
      2 tc=tokenizer.tokenize("Hello, my dog is cute")
----> 3 ec=tokenizer.convert_tokens_to_ids(tc)

1 frames
/content/ALBERT/tokenization.py in convert_by_vocab(vocab, items)
    209   output = []
    210   for item in items:
--> 211     output.append(vocab[item])
    212   return output
    213 

KeyError: '[UNK]'

>

**Comment by aarmstrong78** [comment]
If you only pass the .vocab file the init function will fall back on the Basic and Wordpiece tokenizers, which use [UNK].  You need to pass the spm model name as well:

tokenizer=tokenization.FullTokenizer("/content/30k-clean.vocab", spm_model_file="/content/30k-clean.model")

**Comment by JKP0** [comment]
Thanks! @aarmstrong78
