### ISSUE TITLE
LookupError: No gradient defined for operation 'module_apply_tokens/bert/encoder/transformer/group_0_11/layer_11/inner_group_0/ffn_1/intermediate/output/dense/einsum/Ein$um' (op type: Einsum)

### ISSUE THREAD

**Issue by astrongstorm** [google-research/ALBERT#94]
I am using run_classifier_with_tfhub with  --albert_hub_module_handle=https://tfhub.dev/google/albert_base/2.

I am getting error like "LookupError: No gradient defined for operation 'module_apply_tokens/bert/encoder/transformer/group_0_11/layer_11/inner_group_0/ffn_1/intermediate/output/dense/einsum/Ein$um' (op type: Einsum)"

The argument is:
python3 -m run_classifier_with_tfhub --data_dir=../../DataSet/CoLA/ --t
ask_name=cola --output_dir=testing_ttt --vocab_file=vocab.txt --albert_hub_module_handle=https://tfhub.dev/google/albert_base/2 --do_train=True --do_eval=True --max_seq
_length=128  --train_batch_size=32  --learning_rate=2e-05 --num_train_epochs=3.0

I am using tensorflow==1.15.0

**Comment by 0x0539** [comment]
We have regenerated the hub modules using TF1.15.
Please use hub modules with the "/3" suffix. Hub modules with the "/2" suffix will remain broken.
See Jan 7 update in the readme for more info.

**Comment by TheGlobalist** [comment]
I am facing the same issue with the traditional BERt on Colab.
Here's all the specs:

TF --> '1.15.0'
Colab --> '0.7.0'

Code for loading BERt 
```

        input_word_ids = tf.keras.layers.Input(shape=(20,), dtype=tf.int32, name="input_word_ids")
        input_mask = tf.keras.layers.Input(shape=(20,), dtype=tf.int32, name="input_mask")
        segment_ids = tf.keras.layers.Input(shape=(20,), dtype=tf.int32, name="segment_ids")
        #BERt = BERtLayer()([input_word_ids, input_mask, segment_ids])
        bert = hub.KerasLayer("https://tfhub.dev/tensorflow/bert_multi_cased_L-12_H-768_A-12/1", trainable=True)
        pooled_output, sequence_output = bert([input_word_ids, input_mask, segment_ids])
```



Exception thrown

```
`Call initializer instance with the dtype argument instead of passing it to the constructor
Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
input_word_ids (InputLayer)     [(None, 20)]         0                                            
__________________________________________________________________________________________________
input_mask (InputLayer)         [(None, 20)]         0                                            
__________________________________________________________________________________________________
segment_ids (InputLayer)        [(None, 20)]         0                                            
__________________________________________________________________________________________________
keras_layer (KerasLayer)        [(None, 768), (None, 177853441   input_word_ids[0][0]             
                                                                 input_mask[0][0]                 
                                                                 segment_ids[0][0]                
__________________________________________________________________________________________________
bidirectional (Bidirectional)   [(None, None, 512),  2099200     keras_layer[0][1]                
__________________________________________________________________________________________________
concatenate (Concatenate)       (None, 512)          0           bidirectional[0][1]              
                                                                 bidirectional[0][3]              
__________________________________________________________________________________________________
repeat_vector (RepeatVector)    (None, None, 512)    0           concatenate[0][0]                
__________________________________________________________________________________________________
dense (Dense)                   (None, None, 1)      513         repeat_vector[0][0]              
__________________________________________________________________________________________________
activation (Activation)         (None, None, 1)      0           dense[0][0]                      
__________________________________________________________________________________________________
lambda (Lambda)                 (None, 512)          0           bidirectional[0][0]              
                                                                 activation[0][0]                 
__________________________________________________________________________________________________
multiply (Multiply)             (None, None, 512)    0           bidirectional[0][0]              
                                                                 lambda[0][0]                     
__________________________________________________________________________________________________
babelnet (Dense)                (None, None, 26221)  13451373    multiply[0][0]                   
__________________________________________________________________________________________________
domain (Dense)                  (None, None, 9916)   5086908     multiply[0][0]                   
__________________________________________________________________________________________________
lexicon (Dense)                 (None, None, 9916)   5086908     multiply[0][0]                   
==================================================================================================
Total params: 203,578,343
Trainable params: 203,578,342
Non-trainable params: 1
__________________________________________________________________________________________________
enter in train...
WARNING:tensorflow:From /content/Progetto/code/tokenizer.py:125: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instead.

WARNING:tensorflow:From /content/Progetto/code/tokenizer.py:125: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instead.

Done train preparation...
Done label preparatiomn
ciao
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/math_grad.py:1424: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/math_grad.py:1424: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Train on 29740 samples, validate on 7436 samples
2020-02-22 08:36:39.829236: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-02-22 08:36:39.829902: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: Tesla T4 major: 7 minor: 5 memoryClockRate(GHz): 1.59
pciBusID: 0000:00:04.0
2020-02-22 08:36:39.830005: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-02-22 08:36:39.830039: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-02-22 08:36:39.830074: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-02-22 08:36:39.830103: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-02-22 08:36:39.830127: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-02-22 08:36:39.830154: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-02-22 08:36:39.830182: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-02-22 08:36:39.830309: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-02-22 08:36:39.830960: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-02-22 08:36:39.831507: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-02-22 08:36:39.831561: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-02-22 08:36:39.831575: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-02-22 08:36:39.831603: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-02-22 08:36:39.831760: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-02-22 08:36:39.832342: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-02-22 08:36:39.832866: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 14221 MB memory) -> physical GPU (device: 0, name: Tesla T4, pci bus id: 0000:00:04.0, compute capability: 7.5)
2020-02-22 08:36:41.766438: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 367248384 exceeds 10% of system memory.
2020-02-22 08:36:42.267189: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 367248384 exceeds 10% of system memory.
2020-02-22 08:36:43.576576: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 367248384 exceeds 10% of system memory.
2020-02-22 08:36:43.654042: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 367248384 exceeds 10% of system memory.
2020-02-22 08:36:44.099220: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 367248384 exceeds 10% of system memory.
Epoch 1/4
2020-02-22 08:37:05.283924: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-02-22 08:37:08.127005: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at function_ops.cc:250 : Not found: No gradient defined for op: Einsum
Traceback (most recent call last):
  File "model.py", line 128, in <module>
    modello.train(train,label,vocab_label_bn,vocab_label_wndmn,vocab_label_lex, train_dev, label_dev)
  File "model.py", line 92, in train
    callbacks = [checkpoint, early_stopper],
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training.py", line 727, in fit
    use_multiprocessing=use_multiprocessing)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training_arrays.py", line 675, in fit
    steps_name='steps_per_epoch')
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training_arrays.py", line 394, in model_iteration
    batch_outs = f(ins_batch)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/backend.py", line 3476, in __call__
    run_metadata=self.run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1472, in __call__
    run_metadata_ptr)
tensorflow.python.framework.errors_impl.NotFoundError: [_Derived_]No gradient defined for op: Einsum
	 [[{{node Func/_36}}]]
	 [[training/Adam/gradients/gradients/keras_layer/cond/StatefulPartitionedCall_grad/PartitionedCall/gradients/StatefulPartitionedCall_grad/PartitionedCall/gradients/StatefulPartitionedCall_grad/SymbolicGradient]]`
```

**Comment by RobRomijnders** [comment]
Does the hub module have multiple tags? If so, did you tried any other?

I faced a similar error with a different hub module. It turns out I was using the incorrect tag.
